name: Email Step Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002806@ds.study.iitm.ac.in
        run: echo "Hello, world from 24f1002806@ds.study.iitm.ac.in!"
